main: com.gmail.cjmiller721.ServerPack.Main
name: ServerPack
version: 1.0
author: CJ Miller
description: Contains all the basic funcionality of the Free the Beast Server
commands:
    ptime:
        description: Sets the player's time to the given input.
        usage: /<command> [reset|set] (time) (true|false)
        permission: serverPack.time
    pweather:
        description: Sets the player's weather to the given input.
        usage: /<command> [reset|set] (clear|rain)
        permission: serverPack.weather
    workbench:
        description: Opens up the 3x3 crafting window.
        usage: /<command>
        permission: serverPack.bench
    tpa:
        description: All Teleportation commands.
        usage: /[tpa|tpahere|tpaccept] (Player)
        permission: serverPack.tpa
        aliases: [tpahere, tpaccept]
    friend:
        description: Adds ability to add/remove friends for the tpa system.
        usage: /<command> [add|remove] [Player]

